/**
 * Spring Boot auto-configuration and configuration properties for optional {@code contract-java} integrations.
 *
 * <p>This package contains the starter's supported Boot-facing API; integrations remain conditional and configurable.
 *
 * <p>The starter does not add proxy-based or reflection-based contract
 * enforcement. Contract checks are still generated by {@code contract-core}.
 * The Boot integrations provide conditional actuator information and an
 * opt-in servlet exception resolver for contract-java runtime bridge
 * violations.
 */
@NullMarked
package media.barney.contract.spring;

import org.jspecify.annotations.NullMarked;
